### ISSUE TITLE
Audio Mixers Sometimes Being Ignored

### ISSUE THREAD

**Issue by macfire19** [Garmichael/Boomerang2D#1]
Sound Effects (Specifically those assigned in SFX Pools in the Actor Studio) are not controlled by any of the audio mixers.

Crossfading from Background Music A to B does not function, and will play both tracks at default volume simultaneously.

-Related: The first Camera View always uses Background Music B audio channel, and the second view will use A.

https://user-images.githubusercontent.com/89697173/197311358-43c51e42-82ca-469f-b0c9-9b868511c253.mp4

https://user-images.githubusercontent.com/89697173/197311966-61033d0b-30b6-4fe5-8885-f112d2ba315c.mp4

**Comment by Garmichael** [comment]
This has been fixed!
