### ISSUE TITLE
Saved Brushes Do Not Retain the "Treat Edge as Solid" Selection Between Project Loads

### ISSUE THREAD

**Issue by macfire19** [Garmichael/Boomerang2D#2]
If you have a map (or multiple maps and/or layers) which used a brush with the "Treat Edge as Solid" selection box ticked and then save the terrain, it functions as you would expect.

However, the next time you start up the Unity Editor project itself, the state switches back to off across the entire project.  Which means that for each instance of the use of this feature, you must edit the terrain to tick it and reapply it every time you return to the project.

**Comment by Garmichael** [comment]
This has been fixed!
